### ISSUE TITLE
How to  use method crypt(_:algorithm:data:key:iv:aData:tagLength:) for GCM? Gettingg error  [crypt(_:algorithm:data:key:iv:aData:tagLength:)] AppName.CC.CCError: paramError (-4300)

### ISSUE THREAD

**Issue by yogeshpadekar** [soyersoyer/SwCrypt#13]
Hi,
I am using SwCrypt to implement GCM in my app.
Below is the list of Parameter values I pass:
opMode: .encrypt
algorithm: .aes
data: stringToEncrypt.data(using: .utf8)!
key: keyString.data(using: .utf8)!
iv: Random data of length 12 bytes
aData: Random data of length 20 bytes (I'm not sure what this parameter is for)
tagLength: 128

I get the error [crypt(_:algorithm:data:key:iv:aData:tagLength:)] AppName.CC.CCError: paramError (-4300)
I am unable to understand which parameter I am passing with wrong value

**Comment by soyersoyer** [comment]
The tagLenght parameter is in bytes, so please use 16 instead of 128.

**Comment by yogeshpadekar** [comment]
Hi,
Thanks for responding.
I did the suggested change and still getting the same error. Please guide.

**Comment by soyersoyer** [comment]
What is your key? The AES key should be 128 or 256 bit length.

**Comment by yogeshpadekar** [comment]
Hi, That worked. I was using a shorter key. Made it 128 bits long and its working.
