### ISSUE TITLE
Can't encrypt long messages

### ISSUE THREAD

**Issue by tylerweitzman** [soyersoyer/SwCrypt#15]
Anything above 192 bytes fails to encrypt.

To replicate, try running  testEncryptDecryptOAEPSHA256() in SwCryptTests.swift with longer testData, for example,

		let testData = "This is a test string and I am now making it even longer lke so long that you wo'nt eve nasdf asdjf asdkjf kasdjf kasdjf kasjdf kasjdfk ajsdkf ajskdf jaskdfj askldf jalkwej faowiejf aiw asdkfj aksdjf kasdjfk asjdkf jaskdf jkasdfj kasdjf kasdjf kasjdkf ajsdkf ajskdfj aksdjfkajfiwef wef wef we f".data(using: String.Encoding.utf8)!

**Comment by soyersoyer** [comment]
Yes, this is how the RSA works. You can't encrypt longer messages than the key.
If you want to work with longer messages, you can encrypt a symmetric key with RSA and then use it with a symmetric cipher to encrypt the message.
IMHO if you are working on a new project, you should consider the swift-sodium project too.
