### ISSUE TITLE
tag parameter in encrypt and decrypt RSA

### ISSUE THREAD

**Issue by qazalIOS** [soyersoyer/SwCrypt#18]
what is tag parameter in this method  : 
 try CC.RSA.encrypt(data!, derKey: publicKey, tag: data!, padding: .pkcs1, digest: .none)
thanks.

**Comment by WillBishop** [comment]
Someone? Anyone? I'd like to know also

**Comment by soyersoyer** [comment]
The tag parameter is the L in here:
https://tools.ietf.org/html/rfc8017#section-7.1.1
The .pkcs1 padding doesn't use that parameter.

**Comment by lixxlixxlixx** [comment]
Only your RSA is best used
Thanks soyersoyer
