### ISSUE TITLE
Incorrect documentation on sign/verify?

### ISSUE THREAD

**Issue by tussock** [soyersoyer/SwCrypt#2]
Hey there,

I've been using your swcrypt code in my app. Its very useful, so thank you very much. Its the only one that seems to include both pub key and symmetric algs together, without forcing me to use the keychain (like Heimdall does).

However I was signing some data and found that the signature kept failing.

Your doc says: 

 ```
        let sign = try? CC.RSA.sign(testMessage, derKey: privKey, padding: .pss,  digest: .sha256, saltLen: 16)

         let verified = try? CC.RSA.verify(testMessage, derKey: pubKey, padding: .pss, digest: .sha256, saltLen: 16, signedData: sign!)

```

which kind of implies that you pass the message data in to the sign and verify function. But I found it fails with more than about 100 bytes. Looking at your code for sign, the first parameter is actually:
```
        func sign(hash: NSData, derKey: NSData...

```
It seems that the code is actually used to sign a hash rather than to sign raw data. Do your sample code probably should be something like this:(from my unit tests)
```
        let data = randomLargeData(10240)

        let hash = CC.digest(data, alg: .sha256)

        let sign = try? CC.RSA.sign(hash, derKey: privateKey, padding: .pkcs1,
                                    digest: .sha256)

        XCTAssertNotNil(sign, "Failed to sign")

        let verified = try? CC.RSA.verify(hash, derKey: publicKey, padding: .pkcs1, digest: .sha256, signedData: sign!)

        XCTAssertNotNil(verified, "Failed to calculate verification")

        XCTAssertTrue(verified!, "Failed to verify")

```

This raises a question... why are we passing a digest name to the signing function? Is it required? The call to CCRSACryptorSign does seem to require it, but why? Does the digest passed in to sign() need to be the same as the digest used to hash the message?

Also... note that your doc indicates "padding: .pss". That doesn't exist.
lastly the saltLen parameter is no longer used.

Again... thanks for the library.

**Comment by soyersoyer** [comment]
RSASSA-PSS was added in c9d67a99c4d20b0ed, and the digest is calculated inside the sign/verify now (like in the rfc3447). Please try it with the newest version.

**Comment by tussock** [comment]
Yes - thats fixed it. Nice.

One other question - am I right in that I can choose between aes128 and aes256 by passing in 16 and 32 byte keys? I am trying to decrypt the results using openssl - so I need to have the chosen algorithm right.

**Comment by tussock** [comment]
Got it (i.e. I can now decrypt the results of SwCrypt with openssl.)

When I pass in a 256 bit key, it uses aes256 with 128bit block size. I'm going to guess that if I use a 128 bit key, it will use aes128 with a 128 bit block size.

Interestingly, I can use a 256byte key, 256 byte IV to SwCrypt's crypt, and it still uses aes256 with 128 bit block size. In that case, openssl refuses to decrypt because the IV doesn't match the block size.

**Comment by soyersoyer** [comment]
AES block size is always 128 bit. Yes, the AES mode depends on the key size. The IV should be the same size as the selected algorithm's block size. I am going to add some check for it.
