### ISSUE TITLE
Converting the Data type from CC.HMAC to a string

### ISSUE THREAD

**Issue by jaymutzafi** [soyersoyer/SwCrypt#28]
Hi @soyersoyer,

The API i am working with wants a string of the hashed message.

So I am using `let sign = CC.HMAC(data, alg: .sha512, key: key)`
but then I need to convert `sign` which is of type Data, into a String. 

But no matter how I do it, I can't get a string that works. 

If I am using `let signString = String(describing: sign)', the string that comes to literally be the characters: "64 Bytes" (so it took the size of sign and made that the String).

When I try `String(decoding: sign, as: UTF8.self)` I get a string which is a row of unicodes (and not the characters they represent).

Any idea how I generate a string from the result of CC.HMAC? Is there another function I can or should be using?

Thanks

**Comment by soyersoyer** [comment]
You can use the Data's hexadecimalString() extension.

Here you can see how it works:
https://github.com/soyersoyer/SwCrypt/blob/8c8259da1326ccdcfff64006c4e461a0b8755c6e/SwCrypt/SwCrypt.swift#L2042
