### ISSUE TITLE
Swift 4.1 compile warnings 

### ISSUE THREAD

**Issue by chenyunguiMilook** [soyersoyer/SwCrypt#29]
since Apple just formally released Swift 4.1, I have found this library has some compile warnings. 
SwCrypt.swift:742:18: Overlapping accesses to 'result', but modification requires exclusive access; consider copying to a local variable

**Comment by RomanVolkov** [comment]
just make a variable near result
let count = result.count

and use count instead of result.count inside withUnsafe.... closure

**Comment by soyersoyer** [comment]
fixed in #31
