### ISSUE TITLE
is it possible to get an objective-c version?

### ISSUE THREAD

**Issue by yayang** [soyersoyer/SwCrypt#3]
I have tried to use the way invoke swift code from object-c, but as RSA is an inner class, seems not easy to make it work. Does anyone has any idea?
What I really like is the function of RSA public/private key generation.

**Comment by soyersoyer** [comment]
I think you can use swift code in objective-c. But I don't know how (and why).

**Comment by jostster** [comment]
@soyersoyer it would be great if you could make this compatible for both swift and obj-c. Alot of projects are still obj-c and have yet to be migrated over to swift. The way this swift library is currently made, it isn't possible to be used in an obj-c project.
