### ISSUE TITLE
RSA decrypt failure on iOS 8.1,please help

### ISSUE THREAD

**Issue by dearwayne** [soyersoyer/SwCrypt#30]
Xcode: 9.3.1
Code:
```Swift
let data = "Hello Test".data(using: .utf8)!
let (privateKey, publicKey) = try! CC.RSA.generateKeyPair(1024)
// encrypt
let encrypted = try! CC.RSA.encrypt(data, derKey: publicKey, tag: Data(), padding: .pkcs1, digest: .none)
// decrypt
do {
    let (decrypted,_) = try CC.RSA.decrypt(encrypted, derKey: privateKey, tag: Data(), padding: .pkcs1, digest: .none)
    print("decrypted:\(String(data:decrypted, encoding:.utf8)!)")
}catch{
    print("decrypt fail")
}

```
decypt failure on Simulator:iPhone 5s 8.1,but success on  Simulator: iPhone SE 11.3.

```C++
CCCryptorStatus 
CCRSACryptorDecrypt(
    CCRSACryptorRef privateKey, 
    CCAsymetricPadding padding, 
    const void *cipherText, 
    size_t cipherTextLen,
    void *plainText, 
    size_t *plainTextLen, 
    const void *tagData, 
    size_t tagDataLen, 
    CCDigestAlgorithm digestType)
__OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_5_0);
```

It should be support iOS 5.0 and upper,But why decrypt failure on iOS 8.1?

**Comment by soyersoyer** [comment]
Please send me what was the error.

**Comment by dearwayne** [comment]
> Please send me what was the error.

The error:
SwCrypt.swift:1139: [decrypt(_:derKey:tag:padding:digest:)] SwCryptTest.CC.CCError: decodeError (-4304)

**Comment by soyersoyer** [comment]
Thanks!
It looks like it's a bug in the Apple's CommonCrypto or CoreCrypto components. The good news it was disappeared in the iOS 8.3.

**Comment by fukemy** [comment]
i got same problem when decode base64 string like this:
```
jH1pRwsdUmuqFZIfUIFux25Dbk8LY7gyteiAlQXeW8nOirUIHzzYvadBkmMQNhGqB19bd74tnCbyv8iQwovUpZmxleCsYWFCgzqkx+jQ9TGE4AavwUxJcrdjkXc7AOfQtJHfcgHMVziKrKiZNXi3j3tPIAhA+xFxjZTcSdssIUhcWv9nuPJcjgj18++qd6nL07LVEkqyHqENhX8HnwbWJ8jjeavoO6MV03nCTG2zqOnLThreoTSXl0HX8nhKRim/sklYslYFTXtiMwSY/VtGE5nq7qHgndRDOdJk15w8pS36uuuYbBbhNah9dNT38aHUt0cpZKISMZSghcC6+K1RMg==
```

using RSA256 like server, i got data but can not convert to string

```
            guard let data = Data(base64Encoded: dataStr) else { return }
            let d = try? CC.RSA.decrypt(data, derKey: priv, tag: Data(), padding: .oaep, digest: .sha256)
            guard let decryptData = d else { return }
            print("data: \(String(data: decryptData.0, encoding: .utf8))")
```

always print nil

**Comment by isabsent** [comment]
The same problen in the code:

    guard let encryptedData = Data(base64Encoded: dataStrEncryptedBase64) { return }
    let derKeyPrivate = try SwKeyConvert.PrivateKey.pemToPKCS1DER(privateKey)            
    let data =  try CC.RSA.decrypt(encryptedData, derKey: derKeyPrivate, tag: Data(), padding: .pkcs1, digest: .sha1).0

Error:

    SwCrypt.swift:1136: [decrypt(_:derKey:tag:padding:digest:)] Messenger.CC.CCError: decodeError (-4304)

**CC.RSA.decrypt** method:

    public static func decrypt(_ data: Data, derKey: Data, tag: Data, padding: AsymmetricPadding, digest: DigestAlgorithm) throws -> (Data, Int) {
        let key = try importFromDERKey(derKey)
        defer { CCRSACryptorRelease!(key) }

        let blockSize = getKeySize(key)

        var bufferSize = blockSize
        var buffer = Data(count: bufferSize)

        let status = withUnsafePointers(data, tag, &buffer, {
            dataBytes, tagBytes, bufferBytes in
            return CCRSACryptorDecrypt!(
                key,
                padding.rawValue,
                dataBytes, data.count,
                bufferBytes, &bufferSize,
                tagBytes, tag.count,
                digest.rawValue)
            })
            guard status == noErr else { throw CCError(status) }// <-- Throwing here
            buffer.count = bufferSize

            return (buffer, blockSize)
    }
