### ISSUE TITLE
AES key derivation is vulnerable to brute force attack

### ISSUE THREAD

**Issue by pmilosev** [soyersoyer/SwCrypt#38]
The getAES128Key and getAES256Key methods are prone to brute-force attacks.
Basically the key is computed as MD5(password + iv[0..7]). Given that the IV is a public info, the implementation can be reduced to MD5(password).

MD5 is a very fast hashing function and is also vulnerable to collisions. This means that an attacker can compute hashes fast and also needs to search a smaller space.

But even if the IV was not public, or if another hashing function would have been used (e.g. SHA2) the issue remains.

The key derivation should be based on a password based key derivation function such as bcrypt or PBKDF2 (with high number of iterations).

**Comment by soyersoyer** [comment]
Thank you for your comment. The PEM.EncryptedPrivateKey class is compatible only with the OpenSSL's PKCS#1 AES128, AES256 key encryption, and that old stuff works in this way.
I can implement the PKCS#8 key encryption too, if somebody wants to use.

**Comment by OveysSafarnejad** [comment]
there is limit in encoding data with RSA ,encryption for bytes lower than 245 is available only.
is it possible to make it larger?

**Comment by soyersoyer** [comment]
No, this is how the RSA works.
If you want to work with longer messages, you can encrypt a symmetric key with RSA and then use it with a symmetric cipher (eg.: AES) to encrypt the message.

**Comment by pmilosev** [comment]
OK ... I was actually doing a review as we are interested in integrating the library in one of our projects and noticed this strange key derivation ... I didn't pay attention it is part of some closed context which mandates this behavior.
