### ISSUE TITLE
Working with Server Side Swift - Vapor

### ISSUE THREAD

**Issue by eloit** [soyersoyer/SwCrypt#40]
I've been using the this package with great success under Vapor & Xcode producing Server Side services.  Now that I am trying to move it to a docker container under linux I am getting a number of build errors that I never had before.  

Has anyone got this running on swift under linux and a docker container?   (Using Swift 4.2, Vapor 3.1)

**Comment by soyersoyer** [comment]
This library is using the CommonCrypto and Security frameworks. Unfortunately the CommonCrypto and Security frameworks are not implemented in Linux, so this will not work, sorry.
