### ISSUE TITLE
Xcode 10.2 Swift 5 Error:  Ambiguous use of operator '>>'

### ISSUE THREAD

**Issue by ccjiancui** [soyersoyer/SwCrypt#47]
Ambiguous use of operator '>>'

**Comment by tylerccarson** [comment]
I've also been getting this error ever since the update to Xcode 10.2

**Comment by andrebraga** [comment]
`0xff >> UInt8(zeroBits)` works.

**Comment by tylerccarson** [comment]
@andrebraga are you going to issue a PR to fix this? If not I will, my project depends on this library

**Comment by rmtmckenzie** [comment]
Looks like there's a PR in #48

**Comment by Chris-Corea** [comment]
@soyersoyer Thanks for merging #48! Any chance you could publish a version of the cocoapod with the changes?

**Comment by lampego** [comment]
@soyersoyer Could you publish your changes to the Cocoapod?

**Comment by LazyStudio** [comment]
Below is better

let temp = 0xff >> zeroBits
maskedDBBytes[0] &= UInt8(temp)

**Comment by andrebraga** [comment]
Interesting. I happen to agree.

**Comment by hashimotoryoh** [comment]
@lampego 
> @soyersoyer Could you publish your changes to the Cocoapod?

I specified the commit hash 7a2ec26a70f3c2d5e77df21513888acba2ea553e on `Podfile`.
```
pod 'SwCrypt', :git => 'https://github.com/soyersoyer/SwCrypt.git', :commit => '7a2ec26a70f3c2d5e77df21513888acba2ea553e'
```
