### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by soyersoyer** [soyersoyer/SwCrypt#52]
I don't have a Swift5, Xcode 10.2, OS X 10.14 compatible Mac, and I don't want to buy one only for this project.

If you want to be a SwCrypt maintainer, please apply here.

Responsibilities:
 - Review, test, accept pull requests
 - Release new versions, push them to cocoapods
 - If you want, you can write better documentation or you can add new features.

Rules:
 - My GitHub account (@soyersoyer) should continue to be one of the owners of the project, but you will have full control over its future direction.

**Comment by LuciesHuman** [comment]
Hey @soyersoyer
As long as I'll be w/ my current company, I expect to be  using SwCryp in some form.
For this foreseeable future, I'll gladly help maintaining. 
I do have some experience w/ pushing to spec repos. 
Best.

**Comment by J-Mendes** [comment]
Hi @soyersoyer 
I don't have much experience with releasing to cocoapods but I think with @LuciesHuman help we can keep the project maintained and updated.

**Comment by soyersoyer** [comment]
Cool! I've added you to the collaborators.
Could you send me your email for the cocoapods account?
My email address: soyer@irl.hu
Thanks!

**Comment by rbrignoni-j** [comment]
Hi @soyersoyer,

If you're still looking for maintainers, we're using SwCrypt over at JUUL Labs, I can help out with maintenance. ryan.brignoni@juul.com
