### ISSUE TITLE
How to use key in string format

### ISSUE THREAD

**Issue by imJustik** [soyersoyer/SwCrypt#7]
Hi, could you help me? I have problem with using key in string format.

`let publicKeyDER = try! SwKeyConvert.PublicKey.pemToPKCS1DER("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1UKYj/9uwlfTe4r6Cz9SaOinnfKVUbWCjA9zHcPm7QfAOZ51KeYsuBauALFyF4xJRrDCbYkzz5+AK5Bu78Nz5PAzP72l+VU/mZcV/krRfAkunW+sefh+CMjckALwzSTEI3dzlVVd+ufqsw7h+tNpoYuUk5HK0QaCx8qPzEeQq98zxNgdhXMwiEZTxSKfplEVqnZCcXwfNygP9ATT5rgLpJGlIyHEGv32kxoCqqVy2iwQ7XN1CdTIJu+X/QzFJ++ZqD0kNGmX/8HP1VA2kuW8VTsKOmXvg/fx2a3BH2SYDzEQH+QrpJFxPj/tKfCmVvufVGJakHLLuMODPtJBh2GptwIDAQAB")`

I have exception Error.invalidKey. How to fix it?

**Comment by yogeshpadekar** [comment]
You should covert the String to Data and then send it

**Comment by soyersoyer** [comment]
PEM keys start with -----BEGIN... header. Please use the headers too.
