### ISSUE TITLE
Compatibility with Swift3.0

### ISSUE THREAD

**Issue by maeda-kazuya** [soyersoyer/SwCrypt#8]
Thank you for your effort, is this compatible with Swift 3.0?

**Comment by bmt22033** [comment]
It doesn't appear to be currently.  I added it to my Swift 3.0 project and....well, things were not good.  I was using it fine with Swift 2.2.

**Comment by EhsanMashhadi** [comment]
Has anyone tried to convert this library to Swift3?

**Comment by Nodepad** [comment]
@EhsanMashhadi I did, have some issues still. Will do a PR in couple of days.

**Comment by Droppix** [comment]
+1

**Comment by Nodepad** [comment]
Made PR with migration #10
